### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by luisjfeliu** [Ibotta/gradle-aspectj-pipeline-plugin#15]
This plugin is currently stored in the JCenter repository, which has [shutdown](https://blog.gradle.org/jcenter-shutdown).

Please migrate to MavenCentral or equivalent so that builds/pipelines do not break.

**Comment by eschlenz** [comment]
We publish only to the Gradle Plugin Repository. Not JCenter. @luisjfeliu Can you elaborate on why you feel there may be some work for us here?

**Comment by luisjfeliu** [comment]
> We publish only to the Gradle Plugin Repository. Not JCenter. @luisjfeliu Can you elaborate on why you feel there may be some work for us here?

@eschlenz thanks for the quick response. If you look at the link I posted earlier (https://blog.gradle.org/jcenter-shutdown), the Gradle team says: 

> The Gradle Plugin Portal implicitly mirrors JCenter currently. If you’re using the Plugin Portal (via gradlePluginPortal() or the URL plugins.gradle.org/m2) to resolve your application’s dependencies, you may be relying on JCenter. You should avoid using the Plugin Portal as a repository, except for Gradle plugin projects.

Also, several files in the plugin repo ([here](https://github.com/Ibotta/gradle-aspectj-pipeline-plugin/blob/develop/buildSrc/build.gradle.kts#L5), [here](https://github.com/Ibotta/gradle-aspectj-pipeline-plugin/blob/develop/build.gradle.kts#L15), and [here](https://github.com/Ibotta/gradle-aspectj-pipeline-plugin/blob/develop/settings.gradle.kts#L17)) are explicitly using `jcenter`.

In any case, even though jcenter is supposed to be available until February 1, 2022, my pipeline has failed on several occasions because it failed to download the ibotta plugin from jcenter (and this is how I discovered the issue):

> FAILURE: Build failed with an exception.
>
> * What went wrong:
> A problem occurred configuring root project 'project'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.ibotta:plugin:1.1.0.
     Required by:
         project :
      > Could not resolve com.ibotta:plugin:1.1.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/ibotta/plugin/1.1.0/plugin-1.1.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/ibotta/plugin/1.1.0/plugin-1.1.0.module'.
               > Read timed out

**Comment by luisjfeliu** [comment]
@eschlenz you may want to try using the ibotta aop plugin in an environment where gradle has not cached it (in order to reproduce the issue).

**Comment by eschlenz** [comment]
@luisjfeliu 10-4. Thanks for the additional context! I'll take a look at this this afternoon and report back.

**Comment by eschlenz** [comment]
@luisjfeliu Just opened a PR for this, FYI

**Comment by eschlenz** [comment]
Preparing a release

**Comment by luisjfeliu** [comment]
> Preparing a release

Thank you!

**Comment by eschlenz** [comment]
@luisjfeliu  Ok. Should be all set! If you want to give version 1.3.0 a go, we'd love to hear back if that resolves the issue for you.

https://github.com/Ibotta/gradle-aspectj-pipeline-plugin/releases/tag/1.3.0

**Comment by luisjfeliu** [comment]
> @luisjfeliu Ok. Should be all set! If you want to give version 1.3.0 a go, we'd love to hear back if that resolves the issue for you.
> 
> https://github.com/Ibotta/gradle-aspectj-pipeline-plugin/releases/tag/1.3.0

Works like a charm! Thank you!
