### ISSUE TITLE
using annotations

### ISSUE THREAD

**Issue by schnaps1981** [Ibotta/gradle-aspectj-pipeline-plugin#21]
Hello!
can i use this plugin in annotations style?

**Comment by eschlenz** [comment]
I'm not 100% sure I understand what you mean. Can you elaborate on what it is you're trying to accomplish?

**Comment by schnaps1981** [comment]
ok. Sorry for my English, so:

 i try to create event tracker in my android app. 
Events which i need to track from my business logic appears in different methods (names of kotlin-functions). So i think good solution is just create annotation class and mark necessary function in business logic
`
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FUNCTION)
annotation class Trigger
`

further in business logic module
`
@Trigger
fun myLogic() {
    //some business logic
}
`
further write tracker logic in @Aspect class like

`
@Aspect 
class KotlinAspect {
         @Before("**@annotation(Trigger**)")
         fun trackEvent() {
               // some tracker logic
         }
}
`

i tried change example project from your repository but it's does not working

**Comment by eschlenz** [comment]
Oh! I understand. Yes, you can absolutely target methods with your own annotation. I'll give you an example that I have working locally.

Here is the annotation class code:
```
package com.ibotta.gradle.aop.kotlin

@kotlin.annotation.Retention(AnnotationRetention.RUNTIME)
@Target(
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.PROPERTY_SETTER
)
annotation class Trigger()
```

Here is the aspect code:
```
package com.ibotta.gradle.aop.kotlin

import org.aspectj.lang.JoinPoint
import org.aspectj.lang.annotation.After
import org.aspectj.lang.annotation.Aspect
import org.aspectj.lang.annotation.Before

@Aspect
class TriggerAspect {
    @Before("@annotation(Trigger) && execution(* *(..))")
    fun before(joinPoint: JoinPoint) {
        val messageListener = joinPoint.args[0] as MessageListener
        messageListener.onMessage("Kotlin AOP via Trigger annotation triggered.", CallerType.BEFORE_HOOK)
    }
}
```

I added these two classes to my local clone of the repo for testing inside the `sample-kotlin` module. I then modified the `KotlinTargetExample` class to look like this:
```
package com.ibotta.gradle.aop.kotlin

class KotlinTargetExample {
    @Trigger
    fun demonstrateKotlinAOP(messageListener: MessageListener) {
        messageListener.onMessage("Kotlin method with AOP attached is executed.", CallerType.TARGET)
    }
}
```

And when I run the `sample-kotlin` application in an emulator and hit the button to test, I get this (showing it works!):
<img width="422" alt="Screen Shot 2022-05-17 at 12 18 37 PM" src="https://user-images.githubusercontent.com/2137515/168883106-320fab8a-22af-4ab1-af6d-83f88bd1795c.png">

Note the output `Kotlin AOP via Trigger annotation triggered` showing that the new `TriggerAspect` logic ran as a result of using the `@Trigger` annotation.

Hopefully this helps you!

**Comment by schnaps1981** [comment]
I writed @Before just @Before("@annotation(Trigger)") but need @Before("@annotation(Trigger) && execution(* *(..))")

thak you so much!

**Comment by eschlenz** [comment]
Great! Happy to help.
