### ISSUE TITLE
 about code cache.

### ISSUE THREAD

**Issue by forgetman** [Ibotta/gradle-aspectj-pipeline-plugin#22]
is there have some cached things in plugin or somewhere?
i have change my packgae name, but discover the weave file is duplicate the old package code into 'preWeave' and 'postWeave' like the image.

![image](https://user-images.githubusercontent.com/8208866/169227521-d2cf1d8b-a5d6-4721-bafe-8a535bc254fc.png)

i have tried delete build folder, reopen android stuio, import project again, the result are same.
please help me, thx.

**Comment by forgetman** [comment]
my gradle version is 7.2-bin, studio version is 2020.2.1 chipmunk, build gradle is 7.1.3

**Comment by eschlenz** [comment]
What happens when you run `./gradlew clean assembleDebug --no-build-cache`? Does that resolve it?

**Comment by eschlenz** [comment]
@forgetman Any updates? I'm looking to resolve this issue if possible. I'll just close it out if I don't hear back within a few days. Thanks.

**Comment by forgetman** [comment]
Sorry, I've changed all my Java code to Kotlin while I'm waiting for you, and the problem is gone. The scene is gone now. I can't carry out this order of yours

**Comment by forgetman** [comment]
I can try your command if the problem happens again. Thank you very much.
