### ISSUE TITLE
class.jar is occupied

### ISSUE THREAD

**Issue by ghost** [Ibotta/gradle-aspectj-pipeline-plugin#27]
build\intermediates\compile_library_classes_jar\debug\classes.jar、compile_and_runtime_not_namespaced_r_class_jar is always occupied  at compile time

**Comment by eschlenz** [comment]
@LucklyMaster I assume you're having some kind of build issue given those messages, but it would be helpful if you could include a little more context and information. Even better, if you can share a clone of this repo that demonstrates the issue you're having, we'll be able to help even quicker.
