### ISSUE TITLE
Question: Can this produce aspect binary jars?

### ISSUE THREAD

**Issue by th-jtullgren** [Ibotta/gradle-aspectj-pipeline-plugin#28]
Hi,

Can this project produce binary aspects for consumption and weaving in other projects? IE not weave the current project but rather compile the aspects to a jar.

Its different from using a typical AJ plugin in a traditional java project because we wish to write aspects to weave calls to the AOSP and Androidx libs.  Your plugin seems to already have figured out how to load the android SDK into the classpath for compilation so if it can produce binary aspects in a jar or AAR that would be great.

Thanks!

**Comment by eschlenz** [comment]
Hi @th-jtullgren, I believe others have tried and failed to do what you'd like using our plugin. A path towards supporting it also has not presented itself yet. We tried a couple things, but ultimately gave up on this idea for now. If you somehow are able to make it work, and want to contribute back, we'd be open to that.

**Comment by th-jtullgren** [comment]
@eschlenz Thanks for letting me know!
