### ISSUE TITLE
System.err: java.lang.NoSuchMethodError: No static method aspectOf()Lcom/jidu/lib/data_engine/FragmentViewAspect; in class Lcom/jidu/lib/data_engine/FragmentViewAspect; or its super classes 

### ISSUE THREAD

**Issue by DengFX2010105421** [Ibotta/gradle-aspectj-pipeline-plugin#29]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/18223118/188203166-2c1b4f3e-7ec3-4e83-9fa4-346f1d1d1ae4.png">

**Comment by jdvp** [comment]
@DengFX2010105421 can you point to a sample project to see this issue or able to reproduce in sample? Being able to see code would be helpful in triaging

**Comment by tw-lfeliu** [comment]
This error is unrelated to the ibotta aspectj plugin. The error was thrown on the user's code. @DengFX2010105421 you probably need to invalidate the gradle cache and re-build your app. 

@jdvp I recommend closing out this issue.

**Comment by luisjfeliu** [comment]
This error is unrelated to the ibotta aspectj plugin. The error was thrown on the project's code. @DengFX2010105421 you probably need to invalidate the gradle cache and re-build your app.

@jdvp I recommend closing out this issue.

**Comment by DengFX2010105421** [comment]
@jdvp I have solved the issue, just downgrade the version to 1.2.0, cause i use kotlin 1.6.20, while version 1.4.0 needs kotlin 1.7.x. Thanks

**Comment by eschlenz** [comment]
Thanks, community, for helping out with this one! 👍
