### ISSUE TITLE
Q: can I use this library to hook View methods?

### ISSUE THREAD

**Issue by ibradwan** [Ibotta/gradle-aspectj-pipeline-plugin#32]
Hello there,

Thanks for providing this awesome library.

I'm currently interested in hooking the standard `android.view.View` class public methods. Would it be possible to do this using this library? Or does it only support the code that is being built as part of my application?

Thank you!

**Comment by eschlenz** [comment]
@ibradwan Hey, at this time it can only hook your own code (not 3rd party libraries). We've had some other inquiries along the same lines in the past, and have tried a couple things to allow 3rd party library hooks but weren't successful in getting it to work.

**Comment by ibradwan** [comment]
I see, thanks a lot @eschlenz.
