### ISSUE TITLE
Dumplicate class error

### ISSUE THREAD

**Issue by progratient** [Ibotta/gradle-aspectj-pipeline-plugin#36]
Type xxxAspect$ajcMightHaveAspect is defined multiple times: xxx\build\intermediates\runtime_library_classes_jar\release\classes.jar:xxx/xxxAspect$ajcMightHaveAspect.class, xxx\app\build\postWeave\xxx\xxxAspect$ajcMightHaveAspect.class

The error only occurs when using with pertarget Aspect, why?

**Comment by eschlenz** [comment]
Thanks, but this project is no longer maintained (as indicated on the root README). Sorry.
